# Generated by Django 4.0 on 2024-04-17 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=250)),
                ('fixed_payment', models.BooleanField(default=False)),
                ('pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_currency', models.CharField(choices=[('ETH', 'Etherum'), ('USD', 'US Dollar'), ('BTC', 'Bitcoin'), ('SOL', 'Solana')], default='USD', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filled', 'Filled'), ('unavailable', 'Unavailable')], default='Open', max_length=15)),
                ('role_type', models.CharField(choices=[('remote', 'Remote'), ('permanent', 'Permanent'), ('contract', 'Contract'), ('hybrid', 'Hybrid'), ('full-time', 'Full Time'), ('internship', 'Internship')], default='Permanent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_jobs', to='users.baseuserprofile')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobProposals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_letter', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.baseuserprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='jobs.job')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
